name = "DocInventories"
uuid = "43dc2714-ed3b-44b5-b226-857eda1aa7de"
authors = ["Michael Goerz <mail@michaelgoerz.net>"]
version = "0.2.0+dev"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CodecZlib = "0.7"
Downloads = "1"
TOML = "1"
julia = "1.6"
